project:
  type: book
  output-dir: docs
  resources:
    - data/Scooby.xlsx 
    - data/house_price.csv
    - data/hedonic_ames.csv

book:
  title: "Research Methods for Land Economy"
  author: "Camilo Calderon, PhD"
  chapters:
    - index.qmd
    - supervision_1.qmd
    - supervision_2.qmd
    - supervision_3.qmd
    - supervision_4.qmd
    - supervision_5.qmd
    - supervision_6.qmd
    - supervision_7.qmd
    - formative_test_sup3.qmd
    - formative_test_sup4.qmd
    - solution_formative_test_sup3.qmd
    - solution_formative_test_sup4.qmd
    - solution_formative_task_sup5.qmd
    # later youâ€™ll add more files... supervision_2.qmd, supervision_3.qmd, etc.

format:
  html:
    theme: litera
    number-sections: false
    code-copy: true
    code-overflow: wrap
    css: 
    - styles.css
    - icons.css     # the new emoji polish
    html-math-method: mathjax
